# Generated by Django 5.1.7 on 2025-03-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок запису')),
                ('description', models.TextField(verbose_name='Текст запису')),
                ('author', models.CharField(max_length=100, verbose_name='Автор')),
                ('date', models.DateField(verbose_name='Дата публікації')),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/%Y', verbose_name='Зображення')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/%Y', verbose_name='Відео')),
                ('audio', models.FileField(blank=True, null=True, upload_to='audios/%Y', verbose_name='Аудіо')),
            ],
            options={
                'verbose_name': 'Публікація',
                'verbose_name_plural': 'Публікації',
            },
        ),
    ]
